import { Link } from 'react-router-dom';

const Homepage = () => {
  return <>
    <h2 className="text-2xl mb-3">Homepage</h2>

    <p className="mb-3">This is the index page of your new application.</p>

    <p className="mb-3">It has been generated by Crab and placed in a pages directory. Having a directory specifically for routed elements helps to keep React's cumbersome <code>components</code> directory clear. </p>

    <p className="mb-3">If you want to find out more about Crab, feel free to have a look at the <Link to="/about">about page</Link>.</p>

  </>;
}

export default Home;